/**
 * Application strings in English
 */

export const STRINGS = {
  app: {
    name: 'Smart Delivery Platform',
    tagline: 'Connecting sellers with nearby, verified delivery drivers',
    description: 'A location-aware platform featuring proximity matching, upfront distance and travel time, and end-to-end two-leg route tracking.',
  },
  auth: {
    loginTitle: 'Log in to your account',
    loginSubtitle: 'Enter your email and password to access the platform',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    confirmPasswordLabel: 'Confirm password',
    fullNameLabel: 'Full name',
    phoneLabel: 'Phone number',
    nationalIdLabel: 'National ID number (10 digits)',
    roleLabel: 'Select role',
    loginButton: 'Log in',
    logoutButton: 'Log out',
    signUpButton: 'Sign up',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    genericError: 'Email or password is incorrect.',
    unauthorizedTitle: 'Access Denied',
    unauthorizedSubtitle: 'You do not have permission to view this page with your current role.',
    notFoundTitle: 'Page Not Found',
    notFoundSubtitle: 'The page you requested could not be found.',
    backToHome: 'Back to Home',
  },
  roles: {
    seller: 'Seller',
    driver: 'Driver',
    admin: 'Administrator',
  },
  driverStatus: {
    PENDING: 'Pending Verification',
    APPROVED: 'Approved',
    REJECTED: 'Rejected',
    pendingDesc: 'Your application is currently under administrative review. Once approved, you will gain immediate access to nearby delivery requests.',
    rejectedDesc: 'Your registration was rejected by an administrator. Please review the stated reason below.',
  },
  deliveryStatus: {
    AVAILABLE: 'Available',
    ACCEPTED: 'Accepted',
    PICKED_UP: 'Picked Up',
    ON_THE_WAY: 'On the Way',
    DELIVERED: 'Delivered',
  },
  seller: {
    dashboardTitle: 'Seller Dashboard',
    dashboardSubtitle: 'Manage your delivery requests and track active dispatches',
    createRequest: 'Create Delivery Request',
    totalRequests: 'Total Requests',
    activeRequests: 'Active Deliveries',
    availableRequests: 'Waiting for Driver',
    deliveredRequests: 'Delivered',
    activeBannerTitle: 'Current Active Delivery',
    noActiveRequests: 'No active deliveries right now.',
    allRequests: 'All Delivery Requests',
    reference: 'Reference',
    product: 'Product',
    status: 'Status',
    created: 'Created',
    driver: 'Assigned Driver',
    actions: 'Actions',
    viewDetails: 'View Details',
    noRequestsFound: 'No delivery requests match your filter.',
    createFirst: 'Create your first delivery request to begin dispatching.',
    updatedJustNow: 'Updated just now',
    orderDetailsTitle: 'Order Details',
    waitingForDriver: 'Waiting for a nearby driver to accept...',
    assignedDriverTitle: 'Assigned Driver Details',
  },
  driver: {
    dashboardTitle: 'Available Requests Near You',
    dashboardSubtitle: 'Requests within your current coverage radius sorted by pickup distance',
    locationLabel: 'Your location',
    changeLocation: 'Change',
    radiusLabel: 'Coverage radius',
    refresh: 'Refresh',
    lastUpdated: 'Last updated',
    nearestBadge: 'Nearest',
    viewRequest: 'View Request',
    acceptOrder: 'Accept Order',
    alreadyAcceptedConflict: 'This request was already accepted by another driver.',
    alreadyHasActive: 'You already have an active delivery. Complete your current delivery to accept another.',
    activeDeliveryNotice: 'You have an active delivery in progress.',
    goToActive: 'Go to Active Delivery',
    activeDeliveryTitle: 'Active Delivery',
    emptyNearby: 'No delivery requests found within the selected radius.',
    widenRadiusHint: 'Try widening your radius to see requests further away.',
    markPickedUp: 'Mark as Picked Up',
    markOnTheWay: 'Mark as On the Way',
    markDelivered: 'Mark as Delivered',
    confirmDeliveryModalTitle: 'Confirm Delivery Completion',
    confirmDeliveryModalText: 'Are you sure you have successfully delivered this package to the recipient?',
    deliveryCompletedTitle: 'Delivery Completed Successfully',
    backToDashboard: 'Back to Dashboard',
  },
  admin: {
    dashboardTitle: 'Platform Overview',
    dashboardSubtitle: 'System metrics and pending driver registrations',
    totalDrivers: 'Registered Drivers',
    pendingDrivers: 'Pending Review',
    approvedDrivers: 'Approved Drivers',
    rejectedDrivers: 'Rejected Drivers',
    totalSellers: 'Registered Sellers',
    totalRequests: 'Delivery Requests',
    needsReviewTitle: 'Drivers Needing Review',
    driverManagement: 'Driver Management',
    verificationTitle: 'Driver Verification',
    reviewButton: 'Review Application',
    approveButton: 'Approve Driver',
    rejectButton: 'Reject Driver',
    confirmApproveTitle: 'Confirm Driver Approval',
    confirmApproveText: 'Approving this driver grants immediate access to accept delivery requests on the platform.',
    rejectModalTitle: 'Reject Driver Application',
    rejectModalText: 'Please provide a clear written reason for the rejection. This reason will be shown to the driver on their profile.',
    rejectReasonPlaceholder: 'Enter clear reason for rejection (minimum 10 characters)...',
    verificationChecklist: 'Administrative Verification Checklist',
    checkPhotoMatches: 'Personal photograph matches driver licence identification',
    checkLicenceValid: 'Driver licence is legible, valid, and not expired',
    checkVehicleDetails: 'Vehicle details, model, and plate number are consistent',
  },
  maps: {
    demoMapBadge: 'Demo map (add a Google Maps API key for live maps)',
    distance: 'Distance',
    duration: 'Est. Travel Time',
    totalJourney: 'Total Journey',
    driverToPickup: 'Driver to Pickup',
    pickupToDelivery: 'Pickup to Delivery',
    pickOnMap: 'Pick on map',
    useCurrentLocation: 'Use my current location',
    searchArea: 'Search Amman area...',
  },
  common: {
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    reset: 'Reset',
    close: 'Close',
    filter: 'Filter',
    search: 'Search',
    all: 'All',
    edit: 'Edit',
    profile: 'Profile',
    termsAccepted: 'I agree to the Terms of Service and verify that the provided information is accurate.',
  },
};
